trigger:
- master
- test_wheel

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  variables:
    CIBW_BEFORE_ALL: cd third_party/onnx && git apply ../../onnx_patches/tensor_cow.patch && /opt/python/cp38-cp38/bin/python -m pip install cmake && cp /opt/python/cp38-cp38/bin/cmake /usr/bin/cmake && mkdir temp && curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protobuf-all-3.13.0.tar.gz -o protobuf.tar.gz && tar xf protobuf.tar.gz -C temp && rm -rf protobuf.tar.gz && cd temp/* && mkdir cmake/build && cd cmake/build && cmake -Dprotobuf_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && cmake --build . -j4 && cmake -P cmake_install.cmake && cd ../../../.. && rm -rf temp
    CIBW_BUILD: 'cp3*-manylinux_x86_64'
    CIBW_BUILD_VERBOSITY: 3
  steps:
    - script: git submodule update --init --recursive
    - task: UsePythonVersion@0
    - bash: |
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.5.5
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}

- job: macos
  pool: {vmImage: 'macOS-10.15'}
  variables:
    CIBW_BEFORE_BUILD: pip install cmake
    CIBW_BEFORE_ALL: brew install protobuf
    CIBW_BUILD: 'cp3*-macosx_x86_64'
  steps:
    - script: git submodule update --init --recursive
    - task: UsePythonVersion@0
    - bash: |
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.5.5
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}

- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  variables:
    CIBW_BEFORE_ALL: git clone https://github.com/protocolbuffers/protobuf.git && cd protobuf && git checkout v3.13.0 && cd cmake && mkdir build && cd build && cmake -G "Visual Studio 15 2017 Win64" -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=C:/protobuf_install -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && cmake --build . --config Release -j4 && cmake -P cmake_install.cmake --config Release
    CIBW_ENVIRONMENT: CMAKE_PREFIX_PATH=C:/protobuf_install CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=ON" USE_MSVC_STATIC_RUNTIME=0
    CIBW_BUILD: 'cp3*win_amd64'
  steps:
    - script: git submodule update --init --recursive
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.5.5
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
