name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: vs2017-win2016
    strategy:
      matrix:
        include:
          - python-version: '3.7'
            onnx_ml: 0
            onnx_verify_proto: 0
          - python-version: '3.6'
            onnx_ml: 0
            onnx_verify_proto: 0
          - python-version: '3.7'
            onnx_ml: 1
            onnx_verify_proto: 0
          - python-version: '3.6'
            onnx_ml: 0
            onnx_verify_proto: 1

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create Anaconda environment
      run: C:\Miniconda\Scripts\conda create --yes --quiet --name py${{ matrix.python-version }} -c conda-forge python=${{ matrix.python-version }} numpy libprotobuf=3.11.3 protobuf
      shell: cmd
    - name: Install and test ONNX Optimizer
      shell: cmd
      run: |
        call C:\Miniconda\Scripts\activate py${{ matrix.python-version }}
        python -m pip install --upgrade pip
        # pytest 6.0 made deprecation warnings fail by default, pinning pytest to 5.4.3.
        # TODO replace deprecated function with the suggested one. https://docs.pytest.org/en/stable/deprecations.html#id5
        python -m pip install --quiet pytest==5.4.3 nbval numpy

        git submodule update --init --recursive
        set ONNX_BUILD_TESTS=1
        set ONNX_ML=${{ matrix.onnx_ml }}
        set ONNX_VERIFY_PROTO_3=${{ matrix.onnx_verify_proto }}
        set USE_MSVC_STATIC_RUNTIME=0
        set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_USE_LITE_PROTO=ON

        python setup.py --quiet install
        pytest
        IF NOT %ERRORLEVEL% EQU 0 (
          @echo "pytest failed"
          EXIT 1
        )

        rm -rf .setuptools-cmake-build
        pip install --quiet -e .[mypy]
        python setup.py typecheck
